### ISSUE TITLE
Create `gh-pages` branch for hosting demo

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-action-bar#2]
Not sure if this is already on a list somewhere, but thought I'd throw it out there, since I'd like to consume this guy, but would love to see it in action first.

**Comment by sglanzer** [comment]
Had more people looking for this thing than I anticipated - not a bad problem to have

**Comment by EWhite613** [comment]
The publish should go once the https://github.com/ciena-frost/ember-frost-action-bar/pull/1 is merged as the publish is in the travis build https://github.com/ciena-frost/ember-frost-action-bar/blob/master/.travis.yml#L66

**Comment by sglanzer** [comment]
@job13er the first thing in this repo is the new `subcontext` action bar, but we definitely intend on porting the action bar out of the object browser/modal/bookends and providing that here as well

**Comment by EWhite613** [comment]
https://ciena-frost.github.io/ember-frost-action-bar/
